

```
OPENAI_API_KEY = "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"
GITHUB_API_KEY = "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"
GITHUB_REPO_NAME = "ChatGPTPythonGIT"
GITHUB_REPO_OWNER = "OgeonX"
```